CREATE SEQUENCE seq_initial_sponge START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_product START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_sponge_transformation START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_product_transformation START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_remaining_transformation START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_loss_treshold START WITH 1 INCREMENT BY 1;